import streamlit as st
import torch, joblib
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification

@st.cache_resource
def load_model():
    MODEL_PATH = "./final_model"
    tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_PATH)
    model     = DistilBertForSequenceClassification.from_pretrained(MODEL_PATH)
    encoder   = joblib.load(f"{MODEL_PATH}/label_encoder.pkl")
    model.eval()
    return tokenizer, model, encoder

tokenizer, model, encoder = load_model()

def predict_disease(text: str, top_k: int = 5) -> list:
    """
    Predict disease from a free-text symptom description.
    Returns top_k predictions sorted by confidence (highest first).
    """
    model.eval()
    device = next(model.parameters()).device

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256,
        padding=True,
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        logits = model(**inputs).logits

    probs       = torch.softmax(logits, dim=-1).squeeze().cpu().numpy()
    top_indices = probs.argsort()[::-1][:top_k]

    return [
        {"disease": encoder.classes_[i], "confidence": round(float(probs[i]) * 100, 2)}
        for i in top_indices
    ]

st.title("AI Disease Classifier")
st.markdown("#### About This Project")
st.write(
"**AI Disease & Symptom Analysis Assistant** is a machine learning project designed to help users explore possible health conditions based on their reported symptoms using natural language. " \
"The system is powered by a fine-tuned **DistilBERT Transformer Model** trained on a disease and symptom dataset. Unlike traditional symptom checkers that require users to select predefined symptoms, this application allows users to describe how they feel in their own words. The model analyzes the provided description and returns possible matching conditions with confidence scores. " \
"The goal of this project is to demonstrate how modern Natural Language Processing (NLP) techniques can be applied to healthcare-related text understanding and provide an accessible way to explore symptom patterns. "
)

st.markdown("#### How It Works")
st.write("- Users enter a free-text description of their symptoms.\n- The text is processed using a transformer-based NLP model.\n- The model predicts the most likely matching conditions from the diseases it was trained on.\n- Results are presented as possible matches with confidence estimates.")

st.markdown("#### Help Disclaimer")
st.write("⚠️ **Important: This application is not a medical diagnosis tool.**\n\nThe predictions provided by this system are generated by an artificial intelligence model and are intended for **educational and informational purposes only**. " \
"Do not use this tool for emergency medical situations. If you believe you are experiencing a medical emergency, seek immediate medical assistance.")

user_input = st.text_area("Describe how you feel:", height=120)

if st.button("Predict") and user_input:
    results = predict_disease(user_input, top_k=5)  # same function as above
    st.subheader("Top predictions")
    for r in results:
        st.write(f"**{r['disease'].title()}** — {r['confidence']}% confidence")